<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inventra.Plugins\Inventra.Plugins.InMemory\Inventra.Plugins.InMemory.csproj" />
    <ProjectReference Include="..\Inventra.UseCases\Inventra.UseCases.csproj" />
  </ItemGroup>

</Project>
